/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package demo.craft.user.profile.api

import demo.craft.user.profile.model.CreateBusinessProfileRequest
import demo.craft.user.profile.model.CreateBusinessProfileResponse
import demo.craft.user.profile.model.GetBusinessProfileRequestDetailsResponse
import demo.craft.user.profile.model.UpdateBusinessProfileRequest
import demo.craft.user.profile.model.UpdateBusinessProfileResponse
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestPart
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.RequestHeader
import org.springframework.web.bind.annotation.RequestMethod
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import javax.validation.Valid
import javax.validation.constraints.DecimalMax
import javax.validation.constraints.DecimalMin
import javax.validation.constraints.Max
import javax.validation.constraints.Min
import javax.validation.constraints.NotNull
import javax.validation.constraints.Pattern
import javax.validation.constraints.Size

import kotlin.collections.List
import kotlin.collections.Map

@Validated
@RequestMapping("\${api.base-path:}")
interface BusinessProfileRequestApi {


    @RequestMapping(
            value = ["/user-profile/v1/business-profile"],
            produces = ["application/json"], 
            consumes = ["application/json"],
            method = [RequestMethod.POST])
    fun createBusinessProfile( @RequestHeader(value="x-user-id", required=true) xMinusUserMinusId: kotlin.String
, @Valid @RequestBody createBusinessProfileRequest: CreateBusinessProfileRequest
): ResponseEntity<CreateBusinessProfileResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            value = ["/user-profile/v1/business-profile/request-details"],
            produces = ["application/json"], 
            method = [RequestMethod.GET])
    fun getBusinessProfileRequestDetails( @RequestHeader(value="x-user-id", required=true) xMinusUserMinusId: kotlin.String
,@NotNull  @RequestParam(value = "requestId", required = true) requestId: kotlin.String
): ResponseEntity<GetBusinessProfileRequestDetailsResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }


    @RequestMapping(
            value = ["/user-profile/v1/business-profile"],
            produces = ["application/json"], 
            consumes = ["application/json"],
            method = [RequestMethod.PUT])
    fun updateBusinessProfile( @RequestHeader(value="x-user-id", required=true) xMinusUserMinusId: kotlin.String
, @Valid @RequestBody updateBusinessProfileRequest: UpdateBusinessProfileRequest
): ResponseEntity<UpdateBusinessProfileResponse> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
