demo:
  craft:
    communication:
      kafka:
        bootstrapServers: 'localhost:9092'
        consumer:
          groupId: 'user-profile-workflow'
    user.profile.workflow:
      kafka:
        # subscribe
        userProfileRequestTopic: 'user-profile-request'
        userProfileValidationConfirmationTopic: 'user-profile-validation-confirmation'
        # publish
        userProfileRequestConfirmationTopic: 'user-profile-request-confirmation'

spring:
  application:
    name: user-profile-workflow
  main:
    banner-mode: off
  datasource:
    name: user-profile-workflow
    url: jdbc:postgresql://localhost:5432/user-profile-workflow
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 10
      maximumPoolSize: 25
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    show-sql: true
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration

logging:
  level:
    demo.craft.user.profile.workflow: DEBUG
    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 8085
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15
