package demo.craft.common.domain.kafka.enums

enum class MessageContext {
    USER_PROFILE_REQUEST,
    USER_PROFILE_REQUEST_CONFIRMATION,

    USER_PROFILE_VALIDATION_REQUEST,
    USER_PROFILE_VALIDATION_CONFIRMATION
}