openapi: 3.0.0

info:
  title: User Profile
  description: Open API spec for User Profile
  version: 0.0.1

servers:
  - url: "http://localhost:8080"

paths:
  /user-profile/v1/business-profile:
    get:
      tags:
        - business-profile
      operationId: getBusinessProfile
      summary: Get business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Business profile of the user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBusinessProfileResponse"

    post:
      tags:
        - business-profile
      operationId: createBusinessProfile
      summary: Create a new business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateBusinessProfileResponse"

    put:
      tags:
        - business-profile
      operationId: updateBusinessProfile
      summary: Update business profile of the user
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBusinessProfileRequest"
      responses:
        "200":
          description: Business profile created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateBusinessProfileResponse"

  /user-profile/v1/business-profile/request-details:
    get:
      tags:
        - business-profile-request
      operationId: getBusinessProfileRequestDetails
      summary: Get business profile request details
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/requestId"
      responses:
        "200":
          description: Business profile request details
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetBusinessProfileRequestDetailsResponse"


components:
  parameters:
    userId:
      in: header
      name: x-user-id
      required: true
      schema:
        type: string

    requestId:
      in: query
      name: requestId
      required: true
      schema:
        type: string

  schemas:
    BusinessProfile:
      type: object
      required:
        - companyName
        - legalName
        - businessAddress
        - legalAddress
        - email
        - website
      properties:
        companyName:
          type: string
        legalName:
          type: string
        businessAddress:
          $ref: '#/components/schemas/Address'
        legalAddress:
          $ref: '#/components/schemas/Address'
        pan:
          type: string
        ein:
          type: string
        email:
          type: string
        website:
          type: string

    Address:
      type: object
      required:
        - line1
        - line2
        - city
        - state
        - country
        - zip
      properties:
        line1:
          type: string
        line2:
          type: string
        city:
          type: string
        state:
          type: string
        country:
          type: string
        zip:
          type: string

    RequestStatus:
      type: string
      enum: [IN_PROGRESS, ACCEPTED, REJECTED]

    RequestOperation:
      type: string
      enum: [CREATE, UPDATE]

    GetBusinessProfileResponse:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    CreateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    CreateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string

    UpdateBusinessProfileRequest:
      type: object
      required:
        - businessProfile
      properties:
        businessProfile:
          $ref: "#/components/schemas/BusinessProfile"

    UpdateBusinessProfileResponse:
      type: object
      required:
        - requestUuid
      properties:
        requestUuid:
          type: string

    GetBusinessProfileRequestDetailsResponse:
      type: object
      required:
        - requestDetails
      properties:
        requestStatus:
          $ref: "#/components/schemas/BusinessProfileRequestDetails"

    BusinessProfileRequestDetails:
      type: object
      required:
        - requestId
        - operation
        - status
      properties:
        requestId:
          type: string
        operation:
          $ref: "#/components/schemas/RequestOperation"
        status:
          $ref: '#/components/schemas/RequestStatus'
