demo:
  craft:
    communication:
      kafka:
        bootstrapServers: 'localhost:9092'
        consumer:
          groupId: 'profile-validator'
    profile.validator:
      kafka:
        # subscribe
        userProfileValidationRequestTopic: 'user-profile-validation-request'
        # publish
        userProfileValidationConfirmationTopic: 'user-profile-validation-confirmation'

spring:
  application:
    name: profile-validator
  main:
    banner-mode: off
  datasource:
    name: profile-validator
    url: jdbc:postgresql://localhost:5432/profile-validator
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 10
      maximumPoolSize: 25
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    show-sql: true
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration

logging:
  level:
    demo.craft.profile.validator: DEBUG
    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 9000
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15
