spring:
  application:
    name: user-profile
  main:
    banner-mode: off
  datasource:
    name: user-profile
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimumIdle: 10
      maximumPoolSize: 25
      data-source-properties:
        #loggerLevel: TRACE
        logUnclosedConnections: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
    show-sql: true
  flyway:
    connectRetries: 20
    baselineOnMigrate: true
    baselineVersion: 0
    locations: classpath:db/migration

logging:
  level:
    demo.craft.user.profile: DEBUG
    org:
      springframework:
        web.filter.CommonsRequestLoggingFilter: DEBUG
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

server:
  port: 8080
  shutdown: graceful
  lifecycle:
    timeout-per-shutdown-phase: 15

demo:
  craft:
    communication:
      kafka:
        bootstrapServers: 'localhost:9092'
        consumer:
          groupId: 'user-profile'
    cache:
      redis:
        url: "localhost"
        port: 6379
        readTimeoutInMs: 100
    user-profile:
      kafka:
        userProfileRequestTopic: 'user-profile-request'
        userProfileRequestConfirmationTopic: 'user-profile-request-confirmation'
      cache:
        defaultCacheTtl: 20s #Setting low ttl for demo purpose. In practical, basis the pattern of the change duration we can set the ttl (say we can start with 1 week)